// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQWmBHvY47TSuVv0b170_66Ze1nC16_U',
    appId: '1:945655505836:web:310b8c4c1c9fad93679009',
    messagingSenderId: '945655505836',
    projectId: 'lesson7-e4d27',
    authDomain: 'lesson7-e4d27.firebaseapp.com',
    storageBucket: 'lesson7-e4d27.appspot.com',
    measurementId: 'G-2XWS8MHF19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHXO5mFXJwxzj4-uI6r0zWE7dNLAzt_Y',
    appId: '1:945655505836:android:da3539374f22f5d6679009',
    messagingSenderId: '945655505836',
    projectId: 'lesson7-e4d27',
    storageBucket: 'lesson7-e4d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yRq4GIAAo9lIVNdGRu94UNJtxCpmPxI',
    appId: '1:945655505836:ios:7f55eb56455af70a679009',
    messagingSenderId: '945655505836',
    projectId: 'lesson7-e4d27',
    storageBucket: 'lesson7-e4d27.appspot.com',
    iosBundleId: 'com.example.dars8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yRq4GIAAo9lIVNdGRu94UNJtxCpmPxI',
    appId: '1:945655505836:ios:7f55eb56455af70a679009',
    messagingSenderId: '945655505836',
    projectId: 'lesson7-e4d27',
    storageBucket: 'lesson7-e4d27.appspot.com',
    iosBundleId: 'com.example.dars8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyQWmBHvY47TSuVv0b170_66Ze1nC16_U',
    appId: '1:945655505836:web:73d290ca33a2c711679009',
    messagingSenderId: '945655505836',
    projectId: 'lesson7-e4d27',
    authDomain: 'lesson7-e4d27.firebaseapp.com',
    storageBucket: 'lesson7-e4d27.appspot.com',
    measurementId: 'G-7PF581RZG9',
  );
}
